{% set name = "ggCaller" %}
{% set version = "1.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/samhorsfield96/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: cf2d5751f4f6aa871d9734950120903fde81455ce87387cf24eaec2b50522f3d

build:
  number: 0
  skip: True  # [osx]
  script: {{ PYTHON }} setup.py install --single-version-externally-managed --record=record.txt
  entry_points:
    - ggcaller = ggCaller.__main__:main

requirements:
  build:
    - {{ compiler('c')}}
    - {{ compiler('cxx') }}
    - cmake >=3.4
    - setuptools
    - python >=3
  host:
    - python >=3
    - pybind11
    - llvm-openmp  # [osx]
    - libgomp      # [linux64]
    - seqan3
    - bifrost
    - pthread-stubs
    - biopython
    - zlib
    - bzip2
  run:
    - python >=3
    - bifrost
    - pthread-stubs
    - biopython

test:
  imports:
    - ggCaller_cpp
  commands:
    - ggcaller -h | grep -q "Generates ORFs from a Bifrost graph."

about:
   home: https://github.com/samhorsfield96/ggCaller
   license: MIT
   license_file: LICENSE
   summary: 'a gene caller for Bifrost graphs'
